eclipse-lyo/lyo.designer

- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
#19 AdaptorInterface palette labels should lose the prefix
Fixed labels for all tools in the pallets.
> #19 AdaptorInterface palette labels should lose the prefix

- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
#26  Document the "sematic tab hack" for the external service domain
All loaded Domain Specifications are now available when a Service is
created.
> #26 Document the "sematic tab hack" for the external service domain

- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
Solves issue: #23 Move the capability between services
It is now possible to move (1) Services to different SPs (2) Capabilites
to different services and (3) manged resources to different
capabilities.
That is all arrows in the AdaptorInterface model, except for that
between SPC and SP, since there is only 1 SPC in the model (hence, it
does not make sense)
> #23 Move the capability between services

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateDomainSpecificationConstants.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourcePropertyServices.mtl
Solves issue #18: When classes & property names use reserve names, RDF names get messed up too
RDF names are exactly as they are specified in the model (including
capitalisation).
Fixed for both classes and properties.
> #18 When classes & property names use reserve names, RDF names get messed up too

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceInterface.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourcePropertyServices.mtl
> Accept Set params; return HashSet values

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorManager.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/adaptorInterfaceServices.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/serviceServices.mtl
closes #24: Ambiguous methods created for the Creation Factory in the Mgr class
The problem occur when there are 1+ capabilities (such as
CreationFactory) within an adaptor that manage the same (set of)
resources. This results in multiple methods in the AdaptorManager that
have the same signature.
To remedy, for such 1+ capabilities, append the name of the capability
to the method. For example, a creation factory - with title CF1 - on
Requirement will result in method called "createRequirementForCF1"
This change also made it necessary to have a additional method in
AdaptorManager to handle the creation method from a CreationDialog
(previously, both CreationDialog and CreationFactory) shared the same
createResource method in Manager.
> closes #24: Ambiguous methods created for the Creation Factory in the Mgr class

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateDomainSpecificationConstants.mtl
closes #18: When classes & property names use reserve names, RDF names get messed up too
the relative path for a particular resource no longer has invalid characters such as empty space.
> closes #18: When classes & property names use reserve names, RDF names

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServletListener.mtl
This fix was used to get to the bottom of https://github.com/EricssonResearch/scott-eu/issues/150 but will be useful during any adaptor startup.
> Add logging statements to show what publicURI and servletPath are set

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorClient.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceInterface.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourcePropertyServices.mtl
#61 OslcCoreMissingSetMethodException due to a regression in LyoD
Resource properties of cardinality zero-or-one or zero-or-many are declared as Set. They are constructed as HashSet.
> #61 OslcCoreMissingSetMethodException due to a regression in LyoD

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateIndexJsp.mtl
This allows to ensure that the right web.xml is used just from the first sight:
> Show Servlet Context Name on the homepage

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceInterface.mtl
Remove the Deprecated toHTML() methods from the resource classes.
To view samples of (1) the resource classes (2) the update jsp pages, see the sample-adaptors on
https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/29
**Note** that jsp pages will NOT be regenerated unless they are first removed. This is because we encapsluate the entire jsp code within "protected user code" section.
So, any unremoved jsp pages that still rely on toHtml() methods will fail.
> Remove the Deprecated toHTML() methods from the resource classes.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServiceProviderFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
Fixes https://github.com/eclipse/lyo.designer/issues/89
Closes https://github.com/eclipse/lyo.designer/pull/90
Resulting java code can be found in branch https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/SPFactoryMore, project rm-adaptor.
Sample contains 2 types of SPs: (1) simple single id (2) composite id id1/{id1}/id2/{id2}
> Refactoring ServiceProvider code from the SPC Singleton to the SP-Factory

- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.ecore
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.genmodel
- org.eclipse.lyo.oslc4j.adaptormodel/model/vocabulary.ecore
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/DomainSpecification.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/Specification.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/AdaptorinterfacePackageImpl.java
- org.eclipse.lyo.tools.toolchain.editor/src/toolchain/presentation/ToolchainEditor.java
- org.eclipse.lyo.tools.toolchain.model/src/toolchain/impl/ToolchainPackageImpl.java
- org.eclipse.lyo.tools.vocabulary.editor/src/vocabulary/presentation/VocabularyEditor.java
- org.eclipse.lyo.tools.vocabulary.model/src/vocabulary/Vocabularies.java
- org.eclipse.lyo.tools.vocabulary.model/src/vocabulary/Vocabulary.java
- org.eclipse.lyo.tools.vocabulary.model/src/vocabulary/impl/VocabularyPackageImpl.java
Specify keys for EAttributes within their containing EClass, if they form a set.
This allows for more robust ids when such EAttributes are references
from other parts of hte model (Specifically when references are across
different EMF model files).
For example on how the model will look like, see the file changes on the pull-request on lyo-adaptor-sample-modelling https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/28/files
> Specify keys for EAttributes within their containing EClass

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
Proper handling of application/x-www-form-urlencoded parameters for the CreatioDUI. code was broken.
resulting code can be seen in https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/45
> Proper handling of application/x-www-form-urlencoded parameters for the CreatioDUI. code was broken.

- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.ecore
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.genmodel
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateDomainSpecificationConstants.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceInterface.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/domainSpecificationServices.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourceServices.mtl
- org.eclipse.lyo.tools.adaptormodel.edit/plugin.properties
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/GenerationSettingItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/AdaptorinterfacePackage.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/GenerationSetting.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/AdaptorinterfacePackageImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/GenerationSettingImpl.java
- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
A "do-not-generate" true/false option is provided on a
domainSpecification and/Specification level. This controls whether java
classes are (re)produced.
A visual representation of any generation settings is also provided.
See picture below for illustration.
Tasks:
> Provide control on whether a certain domainSpecification should be generated or not.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceInterface.mtl
Import Vocabulary classes in the resource interface, the same way it is in the resource class.
Currently, generated code of more complex class structures does not compile.
> Import Vocabulary classes in the resource interface, the same way it is in the resource class.

- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
Setting a default non-zero default values for hintHeight & hintWidth for Selection and Creation dialogs. Otherwise, 0-size windows are invisible
.
> Setting a default non-zero default values for hintHeight & hintWidth for Dialogs

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceShapeService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateWebService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/serviceServices.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/webServiceServices.mtl
For the web methods that handle html-requests, add a "return" statement after the statement that dispatches the call to the JSP pages.
Otherwise, the code continues to the part that throws a web exception - even when the the jsp page is being displayed fine.
> Missing "return" statement causes requests (which function otherwise) to also cause an exception

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateGetResourceJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceCollectionJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateServiceProviderHTML.mtl
Service
of the page (instead of bottom of page).
property to be a URI (pointing to its vocabulary definition), instead of
just a a string.
header.
> Some improvements to the jsp/debug pages

- org.eclipse.lyo.tools.designer.product/lyodesigner.product
It is convenient to add the egit feature and perspective. Note that the Java perspective is already included, but not Java EE.
But where do we stop? 
Note that it is currently not possible to work with the generated Java code within LyoDesigner. 
But I am not sure if we want that?
* On one side, it would be nice that user can work in 1 environment.
* On the other, it would be smart to separate the 2 environments: 1 for modelling, and the other for Java development.
What do you think? Opinion appreciated.
> add the egit feature and perspective.

- org.eclipse.lyo.oslc4j.plugins/category.xml
- org.eclipse.lyo.oslc4j.plugins/pom.xml
- pom.xml
Releasing LyoStore as a plugin.
Plus, the plugins have not been build since the release of 4.0.0. Why? 
1. 4.1.0-SNAPSOT is not a SNAPS**H**OT
2. Needed some cleaning of Repositories.
> Store as plugin. Plus build fix

- org.eclipse.lyo.tools.designer.product/lyodesigner.product
Setting the java heap size since Eclipse seems to default to a small size otherwise.
Also, stating explicitly that java-11 is needed.
> Setting the java heap size since Eclipse seems to default to a small size otherwise.

- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.ecore
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.genmodel
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceShapeJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourceServices.mtl
- org.eclipse.lyo.tools.adaptormodel.edit/plugin.properties
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/ResourceItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/AdaptorinterfacePackage.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/Resource.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/AdaptorinterfacePackageImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/ResourceImpl.java
- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
closes #196
Support for the new properties oslc:name and dcterms:description for a ResourceShape.
This is ultimately shown in the JSP page that shows information about a resource shape.
This change assumes the latest change in LyoCore is approved (https://github.com/eclipse/lyo/pull/204)
> Support for the new properties oslc:name and dcterms:description for a ResourceShape.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorManager.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
closes #203.
Besides oslc.paging, the remaining queryParameters (oslc.where and
oslc.prefix) are also consistently handled.
> Consistent support for query parameters (prefix, where, paging)

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
A cleaner way to identify and adjust the size of a queryresult.
Also changed the JSTL dependency scopt to NOT being "provided".
Signed-off-by: Jad El-khoury <jad.el.khoury@scania.com>
> A cleaner way to identify and adjust the size of a queryresult.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorManager.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorResourcesFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/adaptorInterfaceServices.mtl
We want to migrate to simpler class names for Manager and ResourcesFactory class. The names should not contain the name of the applciation name in the class name. Just RestDelegate and ResourcesFactory only.
See the 4 commits in the branch https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/simpler_class_names
Commit0. just basic pre-feature changes.
Commit1. Generator produces a notice to ask user to migrate the old names
Commit2. Manual changes for class renaming according to written instrutions.
Commit3. Generation after renaming, illustrating the little changes that are produced.
> Migrating to simpler class names for Manager and ResourcesFactory class.

- CHANGELOG.md
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.ecore
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.genmodel
- org.eclipse.lyo.tools.adaptormodel.edit/plugin.properties
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/ResourceItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/ResourcePropertyItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/AdaptorinterfacePackage.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/Resource.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/ResourceProperty.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/AdaptorinterfacePackageImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/ResourceImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/ResourcePropertyImpl.java
- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
adding an optional "additionalConstraints" multi-line text attribute on resources ad resourceProperties.
> adding an optional "additionalConstraints" multi-line text attribute on resources ad resourceProperties.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorPackageInfo.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServiceProviderFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateDomainSpecificationConstants.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/adaptorInterfaceServices.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/resourcePropertyServices.mtl
Using the alaternative vocabulary namespace/prefix for a DomainSpec, when one is defined.
> Using the alaternative vocabulary namespace/prefix for a DomainSpec, when one is defined.

- .github/workflows/maven.yml
- CHANGELOG.md
- org.eclipse.lyo.oslc4j.plugins/pom.xml
- pom.xml
p2-maven-plugin since 1.7.0 correctly detects the bytecode level using
latest JDKs again
Closes #0; Closes #00
_(use exactly this syntax to link to issues, one issue per statement only!)_
> Fix osgi.ee=UNKNOWN capability requirement

- org.eclipse.lyo.tools.designer.branding/plugin_customization.ini
ensuring "spacesForTabs" & Unix line separator is always used.
> ensuring "spacesForTabs" & Unix line separator is always used.

- CHANGELOG.md
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateApplicationBinder.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/storeServices.mtl
Provide flexibility to for Store properties to be set via the Environment.
> Provide flexibility to for Store properties to be set via the Environment.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateDomainSpecificationConstants.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/adaptorInterfaceServices.mtl
reverting back the values of the domain names to avoid breaking old code
To see the results of this change, see https://github.com/eclipse/lyo/pull/285
> reverting back the values of the domain names to avoid breaking old code

- org.eclipse.lyo.oslc4j.adaptormodel/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.oslc4j.plugins/pom.xml
- org.eclipse.lyo.tools.adaptormodel.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.codegenerator.feature/feature.xml
- org.eclipse.lyo.tools.codegenerator.ui/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/pom.xml
- org.eclipse.lyo.tools.designer.branding/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.designer.branding/pom.xml
- org.eclipse.lyo.tools.designer.product.feature/feature.xml
- org.eclipse.lyo.tools.designer.product/lyodesigner.product
- org.eclipse.lyo.tools.designer.product/pom.xml
- org.eclipse.lyo.tools.preferences/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.feature/feature.xml
- org.eclipse.lyo.tools.toolchain.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.updatesite/category.xml
- org.eclipse.lyo.tools.updatesite/pom.xml
- org.eclipse.lyo.tools.vocabulary.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model/META-INF/MANIFEST.MF
- pom.xml
Switch to 6.0.0-SNAPSHOT to match Lyo's versioning. 
Next step would be to generate code for Java 17.
> Switch to 6.0.0-SNAPSHOT

- CHANGELOG.md
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
Protect initServerProviders() method
> Protect initServerProviders() method

- org.eclipse.lyo.oslc4j.adaptormodel/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.tools.adaptormodel.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.codegenerator.feature/feature.xml
- org.eclipse.lyo.tools.codegenerator.ui/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/pom.xml
- org.eclipse.lyo.tools.designer.branding/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.designer.branding/pom.xml
- org.eclipse.lyo.tools.designer.product.feature/feature.xml
- org.eclipse.lyo.tools.designer.product/lyodesigner.product
- org.eclipse.lyo.tools.designer.product/pom.xml
- org.eclipse.lyo.tools.preferences/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.feature/feature.xml
- org.eclipse.lyo.tools.toolchain.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.updatesite/category.xml
- org.eclipse.lyo.tools.updatesite/pom.xml
- org.eclipse.lyo.tools.vocabulary.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model/META-INF/MANIFEST.MF
- pom.xml
> 6.0.0.Alpha

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceCollectionJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/staticFiles/generateAdaptorCss.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/staticFiles/generateUiPreviewHelperJs.mtl
Reflecting changes made to RM from RefImpl, including "Update query cap results page & css/js"
- [] This PR expects some manual changes to the generated code. The needed changes are detailed in the CHANGELOG entry.
Closes #286
> Update query cap results page & css/js

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateGetResourceJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateGetResourceLargePreviewJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateGetResourceSmallPreviewJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateGetResourceViewForOslcUIJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceCollectionJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceCreatorClientJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceSelectorClientJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceShapeJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateServiceProviderCatalogHTML.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateServiceProviderHTML.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateSwaggerIndexJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/jspServices.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/staticFiles/generateUiPreviewHelperJs.mtl
- Removes dependency on jQuery
- Updates various CSS classes for Bootstrap 5
- Fixes many issues around popover
Closes #0; Closes #00
_(use exactly this syntax to link to issues, one issue per statement only!)_
> feat: migrate to Bootstrap 5
