eclipse-lyo/lyo.designer

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
Improved all comments in the affected ServiceProviderCatalog class.
This solves issue #25
> Non-existent @param is declared in the javadoc on the generated code #25

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderInfo.mtl
closes #30: SP URI contructors are private
Also closes #36: Extra semicolon inserted in the SP Info class if the
instance id was customised
Providing a public method that can be used to create SP instances based
on SPInfo instances. This method can be dynically called to update the
set of provided SPs.
> closes #30: SP URI contructors are private

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
@berezovskyi is it too late to squeeze this change in?
> Deprecate toHtml methods in the resource pojos.

- org.eclipse.lyo.tools.toolchain.design/pom.xml
fixes #49, but adding necessary packages to allow Sirius design project to build
> Added necessary packages to allow Sirius design project to build

- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.tools.parent/pom.xml
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.design/src/org/eclipse/lyo/tools/toolchain/design/ConfirmDeletionServices.java
- org.eclipse.lyo.tools.updatesite/pom.xml
- pom.xml
Or use `${project.parent.version}` otherwise.
> Remove redundant versions

- org.eclipse.lyo.oslc4j.adaptormodel/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.tools.adaptormodel.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.codegenerator.feature/feature.xml
- org.eclipse.lyo.tools.codegenerator.ui/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.feature/feature.xml
- org.eclipse.lyo.tools.toolchain.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.updatesite/category.xml
- org.eclipse.lyo.tools.updatesite/pom.xml
- org.eclipse.lyo.tools.vocabulary.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model/META-INF/MANIFEST.MF
- pom.xml
Do not merge yet. Waiting for the 2.4.0 to be promoted to stable.
> Bump the version to 4.0.0-SNAPSHOT

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorApplication.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorClient.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServiceProviderFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceShapeService.mtl
I need input on 2 issues in the Application class that I hope someone can help me with. Please see my specific comments on that class (below).
> Generate adaptor code that support oslc4j 4.0.0 (jax-rs2.0)

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorClient.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/main/Generate.java
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/main/GenerateSpecification.java
closes https://github.com/eclipse/lyo.designer/issues/76.
> Updating package name for the oslc4j client.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogService.mtl
closes https://github.com/eclipse/lyo.designer/issues/78
> closes https://github.com/eclipse/lyo.designer/issues/78

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
closes #79 - Add 2 user blocks for the SPC Singleton class.
> closes #79 - Add 2 user blocks for the SPC Singleton class.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServiceProviderFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderCatalogSingleton.mtl
closes #87 createXServiceProvider methods should be moved to xServiceProvidersFactory.
> closes #87 createXServiceProvider methods should be moved to xServiceProvidersFactory

- .mvn/wrapper/.gitignore
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Wrapping maven to use 3.5.2 for LyoDesigner.
Fixes #92
> Wrapping maven to use 3.5.2 for LyoDesigner.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorServletListener.mtl
Solves https://github.com/eclipse/lyo.designer/issues/110
> Allow base path configuration via an ENV variable

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResource.mtl
Resolves https://github.com/eclipse/lyo.designer/issues/96
I tested againts the Requirement class from this branch https://github.com/eclipse/lyo.domains/issues/8.
> Importing the necessary vocabulary constant classes.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateServiceProviderService.mtl
resolves #125. removing exception handling from the jax-rs services.
See the branch for resulting code.
https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/skipStacktrace
> resolves #125. removing exception handling from the jax-rs services.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/serviceServices.mtl
>And I had to CreationDialogs defined, but the generated code resulted in multiple Compile errors in eclipse: in the FromHTML there where 
>some "new URI...", and the compiler complained about missing URI...Exceptions. I cant remember exactly, because I deleted the Dialogs to 
>fix this, since I don't need them...
> Add necessary throws declarations in CreationDialogs service methods.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateResourceService.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceShapeJsp.mtl
resolves #129. 
Better parsing of "describes" and "range" URIs, to try to present a
short name. In best case uri has a "/" or "#" towards the end. but this
cannot be assumed.
Note: if you specify a namespace of "http://your.domain.com/ns" and class named "someName", the class will be shown in the html as "nssomeName".
Good enough to show you that you need to have a "/" or "#"?
> resolves #129. Better parsing of "describes" and "range" URIs, to try to present a short name. 

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateIndexJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceCreatorClientJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateResourceSelectorClientJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateServiceProviderCatalogHTML.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateServiceProviderHTML.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/jsp/generateSwaggerIndexJsp.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/main/generate.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/jspServices.mtl
1. Introduce a header with links to SPC and Swagger pages.
2. Always generate swagger pages, to explain how to integrated
3. better front page
4. In the debug page for an SP, highlight the sample clients at start of
page
> Improved header and swagger pages.

- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.ecore
- org.eclipse.lyo.oslc4j.adaptormodel/model/adaptorInterface.genmodel
- org.eclipse.lyo.tools.adaptormodel.edit/plugin.properties
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/DomainSpecificationItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/ResourceItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.edit/src/adaptorinterface/provider/ResourcePropertyItemProvider.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/AdaptorinterfacePackage.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/DomainSpecification.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/Resource.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/ResourceProperty.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/AdaptorinterfacePackageImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/ResourceImpl.java
- org.eclipse.lyo.tools.adaptormodel.model/src/adaptorinterface/impl/ResourcePropertyImpl.java
- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
Solves #160 but needs some more testing, and thinking.
Can be tested by downloading application from https://download.eclipse.org/lyo/product/binaries/superedge
Adding an ID for each of the Resource and ResourceProperty elements.
This ID is unique within each EMF-EResource (file).
> [WIP] Support Properties With Colliding Names in same DomainSpecs.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorClient.mtl
@berezovskyi Do I have to change ALL versions in all pom files to 4.0.0-SNAPSHOT again?
> Update for hte latest changes of lyo.client.

- org.eclipse.lyo.tools.designer.product/pom.xml
- pom.xml
enabling download stats for plugins, and RPC.
I will need to see if we do actually get stats, before we can merge to master,
> [WIP] enabling download stats for plugins, and RPC.

- org.eclipse.lyo.tools.toolchain.design/description/ToolChainModel.odesign
WIP - transalting from Acceleo queries to AQL for Vocabulary model to start with
> WIP - transalting from Acceleo queries to AQL for Vocabulary model to start with

- LICENSE
- LICENSE.EDL
Just like in https://github.com/eclipse/lyo
> Add EPL 2.0 + EDL licenses

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/staticFiles/generateDelegatedUiHelperJs.mtl
Adding a support function for handling response from iframe of a Selection DUI.
> Adding a support function for handling response from iframe of a Selection DUI.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAuthenticationApplication.mtl
> Use SLF4J for auth login warnings

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateWebService.mtl
Long lines are hard to review in diffs.
> Wrap @Content API annotations

- CHANGELOG.md
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAdaptorResourcesFactory.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/storeServices.mtl
Instead of classes methods, we migrate to instance methods taking us one step closer to dependency injection
> Working with intance methods of ResourcesFactory instead of classes.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/storeServices.mtl
adding some user code blocks for Store generted code.
> adding some user code blocks for Store generted code.

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateAuthenticationApplication.mtl
Resolves compilation errors in the AuthenticationApplication
> Resolve compilation errors in the AuthenticationApplication

- org.eclipse.lyo.oslc4j.plugins/pom.xml
5.0.0.Final for the Lyo Plugins.
> 5.0.0.Final for the Lyo Plugins.

- org.eclipse.lyo.oslc4j.adaptormodel/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.oslc4j.plugins/pom.xml
- org.eclipse.lyo.tools.adaptormodel.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.codegenerator.feature/feature.xml
- org.eclipse.lyo.tools.codegenerator.ui/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/pom.xml
- org.eclipse.lyo.tools.designer.branding/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.designer.branding/pom.xml
- org.eclipse.lyo.tools.designer.product.feature/feature.xml
- org.eclipse.lyo.tools.designer.product/lyodesigner.product
- org.eclipse.lyo.tools.designer.product/pom.xml
- org.eclipse.lyo.tools.preferences/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.feature/feature.xml
- org.eclipse.lyo.tools.toolchain.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.updatesite/category.xml
- org.eclipse.lyo.tools.updatesite/pom.xml
- org.eclipse.lyo.tools.vocabulary.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model/META-INF/MANIFEST.MF
- pom.xml
> 5.0.0.CR release

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
Possiblity to extend Pom.xml file
> Possiblity to extend Pom.xml file

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
Cf. security PR in refimpl.
n/a
> Bump swagger-jaxrs from 2.2.0 to 2.2.7

- org.eclipse.lyo.oslc4j.adaptormodel/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/META-INF/MANIFEST.MF
- org.eclipse.lyo.oslc4j.codegenerator/pom.xml
- org.eclipse.lyo.oslc4j.plugins/pom.xml
- org.eclipse.lyo.tools.adaptormodel.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.adaptormodel.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.codegenerator.feature/feature.xml
- org.eclipse.lyo.tools.codegenerator.ui/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.common/pom.xml
- org.eclipse.lyo.tools.designer.branding/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.designer.branding/pom.xml
- org.eclipse.lyo.tools.designer.product.feature/feature.xml
- org.eclipse.lyo.tools.designer.product/lyodesigner.product
- org.eclipse.lyo.tools.designer.product/pom.xml
- org.eclipse.lyo.tools.preferences/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.design/pom.xml
- org.eclipse.lyo.tools.toolchain.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.toolchain.feature/feature.xml
- org.eclipse.lyo.tools.toolchain.model/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.updatesite/category.xml
- org.eclipse.lyo.tools.updatesite/pom.xml
- org.eclipse.lyo.tools.vocabulary.editor/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model.edit/META-INF/MANIFEST.MF
- org.eclipse.lyo.tools.vocabulary.model/META-INF/MANIFEST.MF
- pom.xml
> 5.1.1.Final release

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/config/generatePomXml.mtl
Eliminates manual management of the dependency versions required by Lyo.
Closes #0; Closes #00
_(use exactly this syntax to link to issues, one issue per statement only!)_
> Switch to lyo-bom

- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateApplicationBinder.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateCorsFilter.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/files/generateLyoAppConfiguration.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/main/generate.mtl
- org.eclipse.lyo.oslc4j.codegenerator/src/org/eclipse/lyo/oslc4j/codegenerator/services/adaptorInterfaceServices.mtl
> finetune AppConfig generation
